GET http://localhost:8000

###
POST http://localhost:8000/api/v0/forecasts 
Content-Type: application/json

{
    "date_time_local": "2030",

    "temperatures": "High 35"

}

###
GET  http://localhost:8000/api/v0/forecasts/


###

GET http://localhost:8000/api/v0/forecast/?date_time_local=2021-05-24 11:00:00 CDT

###

POST http://localhost:8000/api/v0/upload

Content-Type: text/csv
Content-Location: C:\Users\EMMIR_000\Desktop\WinCast\backend\weather_data\weatherstats_winnipeg_forecast_daily.csv
